version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.20
    working_directory: ~/repo

jobs:
  lint:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run: npm run lint

  typecheck:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run: npx tsc --noEmit

  test:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - lint
      - typecheck
      - test
