/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as TosIndexRouteImport } from "./routes/tos/index";
import { Route as TodosIndexRouteImport } from "./routes/todos/index";
import { Route as ProfileIndexRouteImport } from "./routes/profile/index";
import { Route as InvitationsIndexRouteImport } from "./routes/invitations/index";
import { Route as GroupManagementIndexRouteImport } from "./routes/group-management/index";
import { Route as FaqIndexRouteImport } from "./routes/faq/index";
import { Route as AuthIndexRouteImport } from "./routes/auth/index";
import { Route as AboutIndexRouteImport } from "./routes/about/index";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport
} as any);
const TosIndexRoute = TosIndexRouteImport.update({
  id: "/tos/",
  path: "/tos/",
  getParentRoute: () => rootRouteImport
} as any);
const TodosIndexRoute = TodosIndexRouteImport.update({
  id: "/todos/",
  path: "/todos/",
  getParentRoute: () => rootRouteImport
} as any);
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: "/profile/",
  path: "/profile/",
  getParentRoute: () => rootRouteImport
} as any);
const InvitationsIndexRoute = InvitationsIndexRouteImport.update({
  id: "/invitations/",
  path: "/invitations/",
  getParentRoute: () => rootRouteImport
} as any);
const GroupManagementIndexRoute = GroupManagementIndexRouteImport.update({
  id: "/group-management/",
  path: "/group-management/",
  getParentRoute: () => rootRouteImport
} as any);
const FaqIndexRoute = FaqIndexRouteImport.update({
  id: "/faq/",
  path: "/faq/",
  getParentRoute: () => rootRouteImport
} as any);
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: "/auth/",
  path: "/auth/",
  getParentRoute: () => rootRouteImport
} as any);
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: "/about/",
  path: "/about/",
  getParentRoute: () => rootRouteImport
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutIndexRoute;
  "/auth": typeof AuthIndexRoute;
  "/faq": typeof FaqIndexRoute;
  "/group-management": typeof GroupManagementIndexRoute;
  "/invitations": typeof InvitationsIndexRoute;
  "/profile": typeof ProfileIndexRoute;
  "/todos": typeof TodosIndexRoute;
  "/tos": typeof TosIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutIndexRoute;
  "/auth": typeof AuthIndexRoute;
  "/faq": typeof FaqIndexRoute;
  "/group-management": typeof GroupManagementIndexRoute;
  "/invitations": typeof InvitationsIndexRoute;
  "/profile": typeof ProfileIndexRoute;
  "/todos": typeof TodosIndexRoute;
  "/tos": typeof TosIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/about/": typeof AboutIndexRoute;
  "/auth/": typeof AuthIndexRoute;
  "/faq/": typeof FaqIndexRoute;
  "/group-management/": typeof GroupManagementIndexRoute;
  "/invitations/": typeof InvitationsIndexRoute;
  "/profile/": typeof ProfileIndexRoute;
  "/todos/": typeof TodosIndexRoute;
  "/tos/": typeof TosIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/about"
    | "/auth"
    | "/faq"
    | "/group-management"
    | "/invitations"
    | "/profile"
    | "/todos"
    | "/tos";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/about"
    | "/auth"
    | "/faq"
    | "/group-management"
    | "/invitations"
    | "/profile"
    | "/todos"
    | "/tos";
  id:
    | "__root__"
    | "/"
    | "/about/"
    | "/auth/"
    | "/faq/"
    | "/group-management/"
    | "/invitations/"
    | "/profile/"
    | "/todos/"
    | "/tos/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutIndexRoute: typeof AboutIndexRoute;
  AuthIndexRoute: typeof AuthIndexRoute;
  FaqIndexRoute: typeof FaqIndexRoute;
  GroupManagementIndexRoute: typeof GroupManagementIndexRoute;
  InvitationsIndexRoute: typeof InvitationsIndexRoute;
  ProfileIndexRoute: typeof ProfileIndexRoute;
  TodosIndexRoute: typeof TodosIndexRoute;
  TosIndexRoute: typeof TosIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/tos/": {
      id: "/tos/";
      path: "/tos";
      fullPath: "/tos";
      preLoaderRoute: typeof TosIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/todos/": {
      id: "/todos/";
      path: "/todos";
      fullPath: "/todos";
      preLoaderRoute: typeof TodosIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profile/": {
      id: "/profile/";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof ProfileIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/invitations/": {
      id: "/invitations/";
      path: "/invitations";
      fullPath: "/invitations";
      preLoaderRoute: typeof InvitationsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/group-management/": {
      id: "/group-management/";
      path: "/group-management";
      fullPath: "/group-management";
      preLoaderRoute: typeof GroupManagementIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/faq/": {
      id: "/faq/";
      path: "/faq";
      fullPath: "/faq";
      preLoaderRoute: typeof FaqIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/": {
      id: "/auth/";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof AuthIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about/": {
      id: "/about/";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutIndexRoute: AboutIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  FaqIndexRoute: FaqIndexRoute,
  GroupManagementIndexRoute: GroupManagementIndexRoute,
  InvitationsIndexRoute: InvitationsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  TodosIndexRoute: TodosIndexRoute,
  TosIndexRoute: TosIndexRoute
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
